services:
  - type: web
    name: en-nur-membership
    runtime: docker
    repo: https://github.com/Kushtrima/EN-NUR-Membership.git
    branch: main
    
    # Docker-specific settings - Use our startup script
    dockerCommand: /usr/local/bin/startup
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy
    autoDeploy: true
    
    # Environment variables
    envVars:
      # Application Configuration
      - key: APP_NAME
        value: "EN NUR Membership"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://en-nur-membership.onrender.com
      - key: APP_TIMEZONE
        value: Europe/Zurich
      
      # Database Configuration (PostgreSQL)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: en-nur-membership-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: en-nur-membership-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: en-nur-membership-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: en-nur-membership-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: en-nur-membership-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: en-nur-membership-db
          property: connectionString
      
      # Database Connection Settings
      - key: DB_SSLMODE
        value: require
      - key: DB_CONNECT_TIMEOUT
        value: "10"
      - key: DB_QUERY_TIMEOUT
        value: "30"
      
      # Session Configuration
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_ENCRYPT
        value: "false"
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_HTTP_ONLY
        value: "true"
      - key: SESSION_SAME_SITE
        value: "lax"
      
      # Cache Configuration
      - key: CACHE_DRIVER
        value: file
      - key: CACHE_PREFIX
        value: en_nur_membership
      
      # Queue Configuration
      - key: QUEUE_CONNECTION
        value: sync
      
      # Logging Configuration
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: LOG_STACK
        value: single
      
      # Mail Configuration (Namecheap Private Email - Correct Server)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mail.privateemail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        value: info@xhamia-en-nur.ch
      - key: MAIL_PASSWORD
        value: "##~(nWoL-Bi;&&gJBMmb<>g#2#@"
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: info@xhamia-en-nur.ch
      - key: MAIL_FROM_NAME
        value: "EN NUR - Xhamia"
      
      # Payment Configuration (Demo Keys - Replace with real ones)
      - key: STRIPE_KEY
        value: pk_test_demo_key_replace_with_real
      - key: STRIPE_SECRET
        value: sk_test_demo_key_replace_with_real
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_demo_replace_with_real
      
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        value: demo_client_id_replace_with_real
      - key: PAYPAL_CLIENT_SECRET
        value: demo_client_secret_replace_with_real
      
      # File System Configuration
      - key: FILESYSTEM_DISK
        value: local
      
      # Security Configuration
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: FORCE_HTTPS
        value: "true"
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "en-nur-membership.onrender.com"
      
      # PDF Configuration
      - key: DOMPDF_ENABLE_REMOTE
        value: "true"
      - key: DOMPDF_ENABLE_CSS_FLOAT
        value: "true"
      - key: DOMPDF_ENABLE_HTML5_PARSER
        value: "true"
      
      # Performance Configuration
      - key: OPCACHE_ENABLE
        value: "1"
      - key: OPCACHE_MEMORY_CONSUMPTION
        value: "128"
      - key: OPCACHE_MAX_ACCELERATED_FILES
        value: "4000"
      
      # Admin Configuration (Set these in Render dashboard)
      - key: ADMIN_EMAIL
        value: kushtrim.m.arifi@gmail.com
      - key: ADMIN_NAME
        value: "SUPER ADMIN"

databases:
  - name: en-nur-membership-db
    databaseName: en_nur_membership
    user: en_nur_user
    plan: free 