services:
  - type: web
    name: en-nur-membership
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "EN NUR - MEMBERSHIP"
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1c6oqqdbo4c73ckh2e0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: en_nur_membership
      - key: DB_USERNAME
        value: en_nur_user
      - key: DB_PASSWORD
        value: naCuMdU4wCOnsyJ0S6xC1ZO9tRFZfmkn
      - key: DATABASE_URL
        value: postgresql://en_nur_user:naCuMdU4wCOnsyJ0S6xC1ZO9tRFZfmkn@dpg-d1c6oqqdbo4c73ckh2e0-a/en_nur_membership
      - key: SESSION_DRIVER
        value: file
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "EN NUR - MEMBERSHIP"

  - type: pserv
    name: en-nur-membership-db
    env: postgres
    plan: free
    databases:
      - name: en_nur_membership
        user: en_nur_user 