services:
  - type: web
    name: en-nur-membership
    env: php
    plan: free
    buildCommand: |
      # Install Composer dependencies
      composer install --no-dev --optimize-autoloader --no-interaction
      
      # Clear all caches before generating key
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      
      # Generate application key if not set
      if [ -z "$APP_KEY" ]; then
        php artisan key:generate --force
      fi
      
      # Test database connection before migrations
      timeout 30 php artisan tinker --execute="try { DB::connection()->getPdo(); echo 'Database connection successful'; } catch (Exception \$e) { echo 'Database connection failed: ' . \$e->getMessage(); exit(1); }"
      
      # Run migrations
      php artisan migrate --force
      
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "EN NUR - MEMBERSHIP"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: APP_URL
        value: https://en-nur-membership.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1c6oqqdbo4c73ckh2e0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: en_nur_membership
      - key: DB_USERNAME
        value: en_nur_user
      - key: DB_PASSWORD
        value: naCuMdU4wCOnsyJ0S6xC1ZO9tRFZfmkn
      - key: DATABASE_URL
        value: postgresql://en_nur_user:naCuMdU4wCOnsyJ0S6xC1ZO9tRFZfmkn@dpg-d1c6oqqdbo4c73ckh2e0-a/en_nur_membership
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "EN NUR - MEMBERSHIP"

databases:
  - name: en-nur-membership-db
    databaseName: en_nur_membership
    user: en_nur_user
    plan: free 